### PR TITLE
Add pull request template for flint

### LINKED ISSUE #51: Add pull request template
**Is your feature request related to a problem? Please describe.**
Adding a pull request template will make it easier for contributors and maintainers to review the code since they will first have to meet the checklist provided in the pull request template to be eligible for the review.

**Describe the solution you'd like**
Add pull request template markdown file to .github folder.

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #51 Added pull request template in `.github` folder to ease the process of making pull requests and to follow guidelines.

### CODE REVIEW

**Comment by gmajan** [comment]
Sneha, thank you for this. Can you please make sure that the contributor has to sign of? By adding their email contributor confirm that they comply with the DCO:
Sign your message with Signed-off-by: Random J Developer <random@developer.example.org> to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.)
For more see here https://github.com/moja-global/About_moja_global/blob/master/Contributing/How-to-Contribute-Code.md

**Comment by Tlazypanda** [comment]
Hey @gmajan I have updated the pull request :v:

**Comment by gmajan** [comment]
Great. I am with you. Sorry for my ignorance and thank you for the link. Can we turn back the suggestion and then I will merge.
thx

**Comment by Tlazypanda** [comment]
@gmajan please always share your feedback, it always helps to figure out in-case I missed something out or if there is a better way to solve a problem :v: This is the way we will learn and grow together :tada: :octocat:

**Comment by Tlazypanda** [comment]
@gmajan Updated pull request :tada:

**Pull request merged**
